version: '3'
services:
  saikirannallagonda.github.io:
    # build from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm start
